language: go
go:
- '1.10'
go_import_path: github.com/signmykeyio/signmykey
jobs:
  include:
  - stage: test
    name: lint
    script:
    - make lint_install
    - make lint
  - script:
    - make test
    name: unit testing
  - stage: build and package master
    if: branch = master
    sudo: required
    script:
    - make build VERSION=${TRAVIS_BUILD_NUMBER}
    - make fpm_install
    - make fpm VERSION=${TRAVIS_BUILD_NUMBER}
    - make fpm_upload_dev VERSION=${TRAVIS_BUILD_NUMBER}
    env:
    - APTLY_USER=signmykey
    - secure: jvcNE+d1Q7g3y4Gpa3zgpPSydw9jEzRz8/SlHSoLlshpTzz7qUU0B4l+Y7ezV73cm3oj0o+krOp0Nkf5OS83q36+drEEIaXD7bCVeBOucAvLy4q3RUtUFdH6VKSuuCsXcX0Nod5tKbjG3Nkf4NHIRHECRdzFBzyf3g8a9D4mMwYAKrlHHUpLW4gK8NmK56Di191YHgYdYsE3e5e+gttUCuzmio/fT7TEVXFjwSXtucEZiQSvcxEyj7K1Bx9HWJfi4Q6rH8vhN/bsPXNJ9jhpmpdOSVZQKOZALFOcTFApZK6OztDdKqgNv8p5Kw+H73BSq1zYEActbo7+Zkp4oiCMyjvTQuDKax+JE7d25hr5RQnfnGx6syiBtvlEmldT3SLJYGzx3cFwjNYXy3KT5yc04G71+/vEMJWn7vfPOXhfJdPGitsu+LmSPcmONB7J0vuoBbs3btrX3V/kEEmRO5i0pUOnZtVcYvQUWuEABsZ1WhJi/+tVQpVmhtF2Q4WrXByeHhmCGNK4NOINiJGHO5hNKCKsuAnXDGotHW2yw9MGa57lr16VPimZIrapxVsZNA6Wu1f0tLKVLftuRPvu2omGV2EffrFE4mearMV/aFjgbkB5bxU/kzlIDsRTLEG1+7KgHGpJQPVjM7T04svSErxkuK7sUZDq0EtfjMLgAbRxeiA=
  - stage: build and package tag
    if: tag = true
    sudo: required
    script:
    - make build VERSION=${TRAVIS_TAG}
    - make fpm_install
    - make fpm VERSION=${TRAVIS_TAG}
    - make fpm_upload_tag VERSION=${TRAVIS_TAG}
    env:
    - APTLY_USER=signmykey
    - secure: jvcNE+d1Q7g3y4Gpa3zgpPSydw9jEzRz8/SlHSoLlshpTzz7qUU0B4l+Y7ezV73cm3oj0o+krOp0Nkf5OS83q36+drEEIaXD7bCVeBOucAvLy4q3RUtUFdH6VKSuuCsXcX0Nod5tKbjG3Nkf4NHIRHECRdzFBzyf3g8a9D4mMwYAKrlHHUpLW4gK8NmK56Di191YHgYdYsE3e5e+gttUCuzmio/fT7TEVXFjwSXtucEZiQSvcxEyj7K1Bx9HWJfi4Q6rH8vhN/bsPXNJ9jhpmpdOSVZQKOZALFOcTFApZK6OztDdKqgNv8p5Kw+H73BSq1zYEActbo7+Zkp4oiCMyjvTQuDKax+JE7d25hr5RQnfnGx6syiBtvlEmldT3SLJYGzx3cFwjNYXy3KT5yc04G71+/vEMJWn7vfPOXhfJdPGitsu+LmSPcmONB7J0vuoBbs3btrX3V/kEEmRO5i0pUOnZtVcYvQUWuEABsZ1WhJi/+tVQpVmhtF2Q4WrXByeHhmCGNK4NOINiJGHO5hNKCKsuAnXDGotHW2yw9MGa57lr16VPimZIrapxVsZNA6Wu1f0tLKVLftuRPvu2omGV2EffrFE4mearMV/aFjgbkB5bxU/kzlIDsRTLEG1+7KgHGpJQPVjM7T04svSErxkuK7sUZDq0EtfjMLgAbRxeiA=
